apiVersion: apps/v1
kind: Deployment
metadata:
  name: back
  labels:
    name: back
spec:
  replicas: 1
  selector:
    matchLabels:
      name: back
  template:
    metadata:
      labels:
        name: back
    spec:
      containers:
      - image: kontinu/go-expert:v1.0
        name: back
        ports:
          - containerPort: 8080
            name: back
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 1
        resources: {}

---

kind: Service
apiVersion: v1
metadata:
  name: back
spec:
  selector:
      name: back
  type: ClusterIP
  ports:
    - name: web
      port: 80
      targetPort: 8080
