apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    role: myrole
# specification
spec:
  containers:
    - name: apache
      image: httpd
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
    - name: mysql
      image: mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: toor
      ports:
        - name: mysql
          containerPort: 3306
          protocol: TCP
    - name: whoami
      image: jwilder/whoami
      ports:
        - name: whoamiweb
          containerPort: 8000
          protocol: TCP
